version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      #- ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      MSSQL_SA_PASSWORD: '${DB_ROOT_PASSWORD}'
      MSSQL_DB_NAME: '${DB_DATABASE}'
      MSSQL_USER: '${DB_USERNAME}'
    networks:
      - app-network
    depends_on:
      - sqlsrv
  sqlsrv:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    ports:
        - '${DB_PORT:-1433}:1433'
    environment:
      MSSQL_SA_PASSWORD: '${DB_ROOT_PASSWORD}'
      MSSQL_DB_NAME: '${DB_DATABASE}'
      MSSQL_USER: '${DB_USERNAME}'
      MSSQL_PASSWORD: '${DB_PASSWORD}'
      ACCEPT_EULA: '${ACCEPT_EULA}'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
